# Generated by Django 5.2.5 on 2025-12-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='authentication.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='pcs', help_text='Unit of measurement (pcs, box, kg, litre, etc.)', max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_stock', models.IntegerField(default=0)),
                ('low_stock_alert', models.IntegerField(default=0)),
                ('hsn_code', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='authentication.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('movement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('SALE', 'Stock Deducted for Sale'), ('RETURN', 'Stock Added for Return')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, help_text='Bill, Manual Adjustment, Purchase Order, etc.', max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='authentication.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant'], name='inventory_p_tenant__efeeb7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='inventory_p_sku_f85905_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'sku')},
        ),
    ]
