# Generated by Django 5.2.5 on 2025-12-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_profile',
            field=models.ForeignKey(blank=True, help_text='Linked staff profile if this user is an employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authentication.tenant'),
        ),
    ]
